<?php $designer = $this->getCurrentDesigner(); ?>
<?php if ($designer): ?>
    <h1><?php echo $designer->getName(); ?></h1>
    <p><a href="<?php echo $this->helper('dv_designer/designer')->getDesignerUrl($designer); ?>" title="<?php echo $this->escapeHtml($designer->getName()); ?>"><?php echo $designer->getName(); ?></a></p>
    <?php echo $designer->getDescription(); ?>
    <p><a href="<?php echo $this->getUrl('dv_designer/index/index') ?>" title="<?php echo $this->__('Back to Designer Directory'); ?>"><?php echo $this->__('&laquo; Back to Designer Directory'); ?></a></p>
    <?php $productCollection = $this->getProductCollection(); ?>
    <?php if ($productCollection->count() > 0): ?>
        <h2>Products</h2>
        <ul>
            <?php foreach ($productCollection as $_product): ?>
                <li><a href="<?php echo $this->getUrl('catalog/product/view', array('id' => $_product->getId())); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>"><?php echo $_product->getName(); ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php endif; ?>
